### ISSUE TITLE
Installation is not supported for this architecture: arm64

### ISSUE THREAD

**Issue by Lxxyx** [CryogenicPlanet/depp#8]
Trying to install depp but get this error.

```
➜  📦 v2.0.0 npm install -g depp-installer
npm ERR! code 1
npm ERR! path /usr/local/lib/node_modules/depp-installer
npm ERR! command failed
npm ERR! command sh -c node dist/postinstall.js install
npm ERR! /usr/local/lib/node_modules/depp-installer/dist/postinstall.js:107
npm ERR!     throw new Error("Installation is not supported for this architecture: " + process.arch);
npm ERR!           ^
npm ERR!
npm ERR! Error: Installation is not supported for this architecture: arm64
npm ERR!     at parsePackageJson (/usr/local/lib/node_modules/depp-installer/dist/postinstall.js:107:11)
npm ERR!     at Object.<anonymous> (/usr/local/lib/node_modules/depp-installer/dist/postinstall.js:161:16)
npm ERR!     at Generator.next (<anonymous>)
npm ERR!     at /usr/local/lib/node_modules/depp-installer/dist/postinstall.js:36:61
npm ERR!     at new Promise (<anonymous>)
npm ERR!     at __async (/usr/local/lib/node_modules/depp-installer/dist/postinstall.js:20:10)
npm ERR!     at Object.install (/usr/local/lib/node_modules/depp-installer/dist/postinstall.js:160:10)
npm ERR!     at Object.<anonymous> (/usr/local/lib/node_modules/depp-installer/dist/postinstall.js:212:15)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1101:14)
npm ERR!     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
```

**Comment by CryogenicPlanet** [comment]
What OS is this? I'm guessing M1 mac? Haven't tried installing on arm chips will look into it

**Comment by Lxxyx** [comment]
> What OS is this? I'm guessing M1 mac? Haven't tried installing on arm chips will look into it

Yes. M1 mac.

**Comment by CryogenicPlanet** [comment]
Also could you get installing the package directly from go instead of through npm. This will give a better idea if the problem is with the compiled go binary or the post install script

```
go install github.com/cryogenicplanet/depp@latest
```

**Comment by CryogenicPlanet** [comment]
Hey @Lxxyx I setup a macOS `Aarch64` runner and tried to install the file and it works fine, as you can see https://github.com/CryogenicPlanet/depp/runs/4202615408?check_suite_focus=true so I am going to need more info from your side if I am going to be able to diagnose this as I don't have a m1 mac to test myself

**Comment by Lxxyx** [comment]
> Hey @Lxxyx I setup a macOS `Aarch64` runner and tried to install the file and it works fine, as you can see [CryogenicPlanet/depp/runs/4202615408?check_suite_focus=true](https://github.com/CryogenicPlanet/depp/runs/4202615408?check_suite_focus=true) so I am going to need more info from your side if I am going to be able to diagnose this as I don't have a m1 mac to test myself

Still not works when node.js version > 16. @CryogenicPlanet 

Node.js support m1 mac since 16.x, this test running node.js @14. 

> Node.js v14 + m1 mac, works

```
[1/1] scripts.postinstall depp-installer@0.0.10 run "node dist/postinstall.js install", root: "/usr/local/lib/node_modules/depp-installer"
Copying the relevant binary for your platform darwin
Downloading binary from https://github.com/CryogenicPlanet/depp/releases/download/v0.0.10/depp_0.0.10_darwin_x86_64.tar.gz
Unpacked tarball
Wrote binary to out path ./bin/depp
Installed cli successfully
[1/1] scripts.postinstall depp-installer@0.0.10 finished in 46s
All packages installed (53 packages installed from npm registry, used 47s(network 1s), speed 469.24KB/s, json 49(91.11KB), tarball 401.58KB)
```

> Node.js v14 + m1 mac, failed

```
[1/1] scripts.postinstall depp-installer@0.0.10 run "node dist/postinstall.js install", root: "/usr/local/lib/node_modules/depp-installer"
/usr/local/lib/node_modules/depp-installer/dist/postinstall.js:107
    throw new Error("Installation is not supported for this architecture: " + process.arch);
          ^

Error: Installation is not supported for this architecture: arm64
```

**Comment by CryogenicPlanet** [comment]
> Also could you get installing the package directly from go instead of through npm. This will give a better idea if the problem is with the compiled go binary or the post-install script
> 
> ```
> go install github.com/cryogenicplanet/depp@latest
> ```

@Lxxyx Can you try this?

**Comment by Boromir1994** [comment]
@CryogenicPlanet  I did try. For me result is `command not found`
![image](https://user-images.githubusercontent.com/7275424/143578443-2557faad-2797-4a9b-9bb3-4fdb03b60428.png)
![image](https://user-images.githubusercontent.com/7275424/143578507-7c03b598-0b49-4860-a36f-446f9e718205.png)
Node v16.13.0
npm v8.1.0

**Comment by CryogenicPlanet** [comment]
> @CryogenicPlanet I did try. For me result is `command not found` ![image](https://user-images.githubusercontent.com/7275424/143578443-2557faad-2797-4a9b-9bb3-4fdb03b60428.png) ![image](https://user-images.githubusercontent.com/7275424/143578507-7c03b598-0b49-4860-a36f-446f9e718205.png) Node v16.13.0 npm v8.1.0

Hey, you will need to add the go bin to your `.zshrc`
